/**
 * Domain models for the Vuera eyewear platform.
 *
 * These types describe the core entities of the store. They are framework
 * agnostic and shared across the service layer, state stores, and UI.
 */

export type UUID = string;

export type ISODateString = string;

export type Money = number;

export type FrameShape = 'round' | 'square' | 'rectangular' | 'oval' | 'cat-eye' | 'aviator' | 'geometric';

export type FrameMaterial = 'acetate' | 'metal' | 'titanium' | 'wood' | 'mixed';

export type GenderTarget = 'unisex' | 'men' | 'women';

export type LensType = 'single-vision' | 'progressive' | 'reading' | 'non-prescription' | 'sunglasses';

export type ProductStatus = 'active' | 'draft' | 'archived';

export interface ProductImage {
  id: UUID;
  productId: UUID;
  url: string;
  altText: string | null;
  /** Zero-based display order. */
  position: number;
  /** True when the image was generated by the AI try-on pipeline. */
  isAiGenerated: boolean;
}

export interface ProductVariant {
  id: UUID;
  productId: UUID;
  /** e.g. "Mat Black / 52mm" */
  name: string;
  /** Frame size in mm, when applicable. */
  sizeMm: number | null;
  /** Lens tint for sunglasses, null for clear. */
  lensTint: string | null;
  price: Money;
  /** Units available across all warehouses. */
  stock: number;
  sku: string;
}

export interface Product {
  id: UUID;
  slug: string;
  name: string;
  brand: string;
  description: string;
  shape: FrameShape;
  material: FrameMaterial;
  gender: GenderTarget;
  lensType: LensType;
  /** Base price in major currency units (USD). */
  price: Money;
  /** Compare-at price for sale display, null when not on sale. */
  compareAtPrice: Money | null;
  status: ProductStatus;
  /** Average rating 0–5, null before any reviews. */
  rating: number | null;
  reviewCount: number;
  /** Category slugs this product belongs to. */
  categoryIds: UUID[];
  images: ProductImage[];
  variants: ProductVariant[];
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

export interface Category {
  id: UUID;
  slug: string;
  name: string;
  description: string | null;
  parentId: UUID | null;
}

export interface Review {
  id: UUID;
  productId: UUID;
  authorName: string;
  rating: number;
  title: string;
  body: string;
  createdAt: ISODateString;
  /** True when the reviewer purchased through Vuera. */
  verifiedPurchase: boolean;
}

export interface CartItem {
  productId: UUID;
  variantId: UUID;
  name: string;
  image: string;
  unitPrice: Money;
  quantity: number;
}

export interface Cart {
  items: CartItem[];
  /** Subtotal before tax and shipping. */
  subtotal: Money;
  currency: string;
}

export interface Address {
  fullName: string;
  line1: string;
  line2: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  phone: string | null;
}

export type OrderStatus =
  | 'pending'
  | 'paid'
  | 'fulfilled'
  | 'shipped'
  | 'delivered'
  | 'cancelled'
  | 'refunded';

export interface Order {
  id: UUID;
  userId: UUID;
  items: CartItem[];
  status: OrderStatus;
  subtotal: Money;
  shipping: Money;
  tax: Money;
  total: Money;
  currency: string;
  shippingAddress: Address;
  createdAt: ISODateString;
}

export interface UserProfile {
  id: UUID;
  email: string;
  firstName: string | null;
  lastName: string | null;
  avatarUrl: string | null;
  /** Saved face measurements for AR/AI try-on, in mm. */
  faceProfile: FaceProfile | null;
  createdAt: ISODateString;
}

export interface FaceProfile {
  pupillaryDistanceMm: number;
  faceWidthMm: number;
  templeLengthMm: number;
}

/* ------------------------------------------------------------------ */
/* AI feature envelopes — placeholders for future pipelines.          */
/* ------------------------------------------------------------------ */

export interface VirtualTryOnRequest {
  productId: UUID;
  variantId: UUID;
  /** User-uploaded selfie URL or data URL. */
  sourceImageUrl: string;
}

export interface VirtualTryOnResult {
  id: UUID;
  productId: UUID;
  /** Resulting image with glasses composited onto the face. */
  resultImageUrl: string;
  /** Confidence score 0–1 from the fitting model. */
  fitConfidence: number;
  createdAt: ISODateString;
}

export interface RecommendationRequest {
  /** Free-text preferences from the user. */
  prompt: string;
  faceProfile: FaceProfile | null;
  budgetCents: Money | null;
  /** Category slugs to constrain the search. */
  categories: string[];
}

export interface RecommendationResult {
  productId: UUID;
  score: number;
  reason: string;
}
